version: '3.8'

services:
  ehub-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    container_name: ehub-container
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    stdin_open: true

