version: '3.8'

networks:
  ehub-network:


services:
  rabbitmq-service:
    image: rabbitmq:3.11-management-alpine
    expose:
      - 5672
    ports:
      - 15672:15672
    networks:
      - ehub-network

  ehub-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    container_name: ehub-container
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    networks:
      - ehub-network
    stdin_open: true
